services:
  - type: web
    name: nirapod-point-backend
    env: docker
    region: oregon
    plan: starter
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        value: mongodb+srv://mdarafat1661:8EXsGGrmqMFZQe27@nirapodpoint.t3aunut.mongodb.net/?retryWrites=true&w=majority&appName=NirapodPoint
      - key: SPRING_MAIL_USERNAME
        value: hello3210bye@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: zqap tdkc wjbd ilyx
      - key: PORT
        value: "10000"
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxMetaspaceSize=128m"
    buildCommand: ""
    startCommand: ""
